dist: xenial
sudo: required
addons:
        apt:
                packages:
                        - libgudev-1.0-dev
                        - libudev-dev
                        - libgtk-3-dev

language: rust

rust:
        - stable
        - nightly

