[package]
name = "gpsami"
version = "0.1.0"
authors = ["Hubert Figuière <hub@figuiere.net>"]
license = "GPL-3"
edition = "2018"

[dependencies]
glib-sys = "*"
glib = { version="^0.10.0" }
gio = { version="^0.9.0" }
gtk = { version="^0.9.0" }
rustc-serialize = "0.3"
libudev = "0.2.0"
gudev = "^0.9.0"
dirs = "^1.0.4"

gettext-rs = { version = "0.4.4", features = ["gettext-system"] }

[[bin]]
name = "gpsami"
