[package]
name = "gpsami"
version = "0.1.0"
authors = ["Hubert Figuière <hub@figuiere.net>"]
license = "GPL-3"
edition = "2018"

[dependencies]
gtk4 = "^0.4.0"
gtk-macros = "^0.3.0"
serde = { version = "1.0.126", features = ["derive"] }
serde_json = "1.0.64"
libudev = "0.2.0"
gudev = { version = "^0.12.0" }
dirs = "^1.0.5"
once_cell = "1.5"

gettext-rs = { version = "0.4.4", features = ["gettext-system"] }

[[bin]]
name = "gpsami"
